# Generated by Django 4.2 on 2023-04-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_booking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="poi_url",
            field=models.CharField(max_length=255),
        ),
    ]
