# Generated by Django 4.2 on 2023-04-18 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_booking_poi_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bookingId", models.CharField(max_length=255)),
                ("cardNumber", models.CharField(max_length=16)),
                ("cardHolder", models.CharField(max_length=255)),
                ("expiryDate", models.CharField(max_length=5)),
                ("cvc", models.CharField(max_length=3)),
            ],
        ),
    ]
